/**
 * @file test_cross_language_precision.cpp
 * @brief Unit tests for cross-language numerical precision validation
 *
 * This test suite validates that uband_diff correctly identifies files
 * containing the same mathematical constant (π) generated by different
 * programming languages as equivalent.
 *
 * PURPOSE:
 * Different programming languages have different rounding behaviors when
 * formatting floating-point numbers to ASCII text:
 * - C++: std::fixed with banker's rounding (ties to even)
 * - Fortran: format specifiers with traditional rounding
 * - Python: f-strings with banker's rounding
 * - Java: DecimalFormat with half-up rounding
 *
 * Despite these differences, when calculating and printing the same constant
 * (π) to the same precision, all outputs should be considered IDENTICAL by
 * a precision-aware comparison tool.
 *
 * TEST DATA:
 * The test files are generated by scripts in scripts/pi_gen/ and stored in
 * data/. Each file contains π printed at increasing decimal precision:
 *   Line 1: "1  3"         (0 dp)
 *   Line 2: "2  3.1"       (1 dp)
 *   Line 3: "3  3.14"      (2 dp)
 *   ...
 *   Line 15: "15  3.14159265358979"  (14 dp)
 *
 * REGENERATION:
 * To regenerate test data files:
 *   make pi_gen_data
 *
 * @author J.C. Lighthall
 * @date January 2026
 */

#include <gtest/gtest.h>

#include <string>

#include "uband_diff.h"

// Path to data directory relative to test execution directory (build/test/)
static constexpr const char* DATA_DIR = "../../data/";

// Helper to get full path for data file
static std::string getDataFilePath(const std::string& filename) {
  return std::string(DATA_DIR) + filename;
}

/**
 * @brief Test that C++ and Fortran produce identical pi output
 *
 * Both languages calculate π using 4*atan(1) and output with std formatting.
 * Despite any internal representation differences, the ASCII output should
 * be identical at each precision level.
 */
TEST(CrossLanguagePrecisionTest, PiCppVsFortranIdentical) {
  FileComparator cmp(/*user_thresh*/ 0.0, /*hard*/ 9999.0, /*print*/ 0.0,
                     /*debug*/ 0);

  std::string ref = getDataFilePath("pi_cpp_asc.txt");
  std::string test = getDataFilePath("pi_fortran_asc.txt");

  bool result = cmp.compare_files(ref, test);

  const auto& stats = cmp.getCountStats();
  const auto& flags = cmp.getFlag();

  // Files should be completely identical
  EXPECT_TRUE(result) << "C++ and Fortran pi files should compare successfully";
  EXPECT_TRUE(flags.files_are_close_enough)
      << "Files should be considered 'close enough'";

  // All differences should be zero (files are identical)
  EXPECT_EQ(stats.diff_non_zero, 0u)
      << "C++ and Fortran pi should have no non-zero differences";
  EXPECT_EQ(stats.diff_non_trivial, 0u)
      << "C++ and Fortran pi should have no non-trivial differences";
  EXPECT_EQ(stats.diff_significant, 0u)
      << "C++ and Fortran pi should have no significant differences";
}

/**
 * @brief Test that C++ and Python produce identical pi output
 *
 * Both use banker's rounding (round half to even), so outputs should match.
 */
TEST(CrossLanguagePrecisionTest, PiCppVsPythonIdentical) {
  FileComparator cmp(/*user_thresh*/ 0.0, /*hard*/ 9999.0, /*print*/ 0.0,
                     /*debug*/ 0);

  std::string ref = getDataFilePath("pi_cpp_asc.txt");
  std::string test = getDataFilePath("pi_python_asc.txt");

  bool result = cmp.compare_files(ref, test);

  const auto& stats = cmp.getCountStats();
  const auto& flags = cmp.getFlag();

  EXPECT_TRUE(result) << "C++ and Python pi files should compare successfully";
  EXPECT_TRUE(flags.files_are_close_enough);
  EXPECT_EQ(stats.diff_non_zero, 0u);
  EXPECT_EQ(stats.diff_non_trivial, 0u);
  EXPECT_EQ(stats.diff_significant, 0u);
}

/**
 * @brief Test that C++ and Java produce identical pi output
 *
 * Java uses DecimalFormat with half-up rounding, but at the precision levels
 * we test, this should not cause any visible differences.
 */
TEST(CrossLanguagePrecisionTest, PiCppVsJavaIdentical) {
  FileComparator cmp(/*user_thresh*/ 0.0, /*hard*/ 9999.0, /*print*/ 0.0,
                     /*debug*/ 0);

  std::string ref = getDataFilePath("pi_cpp_asc.txt");
  std::string test = getDataFilePath("pi_java_asc.txt");

  bool result = cmp.compare_files(ref, test);

  const auto& stats = cmp.getCountStats();
  const auto& flags = cmp.getFlag();

  EXPECT_TRUE(result) << "C++ and Java pi files should compare successfully";
  EXPECT_TRUE(flags.files_are_close_enough);
  EXPECT_EQ(stats.diff_non_zero, 0u);
  EXPECT_EQ(stats.diff_non_trivial, 0u);
  EXPECT_EQ(stats.diff_significant, 0u);
}

/**
 * @brief Test that Fortran and Python produce identical pi output
 */
TEST(CrossLanguagePrecisionTest, PiFortranVsPythonIdentical) {
  FileComparator cmp(/*user_thresh*/ 0.0, /*hard*/ 9999.0, /*print*/ 0.0,
                     /*debug*/ 0);

  std::string ref = getDataFilePath("pi_fortran_asc.txt");
  std::string test = getDataFilePath("pi_python_asc.txt");

  bool result = cmp.compare_files(ref, test);

  const auto& flags = cmp.getFlag();

  EXPECT_TRUE(result)
      << "Fortran and Python pi files should compare successfully";
  EXPECT_TRUE(flags.files_are_close_enough);
}

/**
 * @brief Test that all four languages produce identical pi output
 *
 * This is the key validation: the same mathematical constant, computed and
 * formatted by four different programming languages with different internal
 * rounding behaviors, should all be recognized as identical by uband_diff.
 */
TEST(CrossLanguagePrecisionTest, AllLanguagesProduceIdenticalPi) {
  const std::vector<std::string> languages = {"cpp", "fortran", "java",
                                              "python"};

  // Compare all pairs
  for (size_t i = 0; i < languages.size(); ++i) {
    for (size_t j = i + 1; j < languages.size(); ++j) {
      FileComparator cmp(0.0, 9999.0, 0.0, 0);

      std::string ref = getDataFilePath("pi_" + languages[i] + "_asc.txt");
      std::string test = getDataFilePath("pi_" + languages[j] + "_asc.txt");

      bool result = cmp.compare_files(ref, test);

      EXPECT_TRUE(result) << "Pi from " << languages[i] << " and "
                          << languages[j] << " should be identical";
      EXPECT_TRUE(cmp.getFlag().files_are_close_enough)
          << "Pi from " << languages[i] << " and " << languages[j]
          << " should be 'close enough'";
      EXPECT_EQ(cmp.getCountStats().diff_significant, 0u)
          << "Pi from " << languages[i] << " and " << languages[j]
          << " should have no significant differences";
    }
  }
}
